language: bash
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script:
  - git clone {{cookiecutter.github_url}}
  - cd {{cookiecutter.template_name}}
  - sudo bash make.sh